GameScore/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;
using GameScore.Areas.HelpPage.ModelDescriptions;

namespace GameScore.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            UriParameters = new Collection<ParameterDescription>();
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ParameterDescription"/> collection that describes the URI parameters for the API.
        /// </summary>
        public Collection<ParameterDescription> UriParameters { get; private set; }

        /// <summary>
        /// Gets or sets the documentation for the request.
        /// </summary>
        public string RequestDocumentation { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the request body.
        /// </summary>
        public ModelDescription RequestModelDescription { get; set; }

        /// <summary>
        /// Gets the request body parameter descriptions.
        /// </summary>
        public IList<ParameterDescription> RequestBodyParameters
        {
            get
            {
                return GetParameterDescriptions(RequestModelDescription);
            }
        }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the resource.
        /// </summary>
        public ModelDescription ResourceDescription { get; set; }

        /// <summary>
        /// Gets the resource property descriptions.
        /// </summary>
        public IList<ParameterDescription> ResourceProperties
        {
            get
            {
                return GetParameterDescriptions(ResourceDescription);
            }
        }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }

        private static IList<ParameterDescription> GetParameterDescriptions(ModelDescription modelDescription)
        {
            ComplexTypeModelDescription complexTypeModelDescription = modelDescription as ComplexTypeModelDescription;
            if (complexTypeModelDescription != null)
            {
                return complexTypeModelDescription.Properties;
            }

            CollectionModelDescription collectionModelDescription = modelDescription as CollectionModelDescription;
            if (collectionModelDescription != null)
            {
                complexTypeModelDescription = collectionModelDescription.ElementDescription as ComplexTypeModelDescription;
                if (complexTypeModelDescription != null)
                {
                    return complexTypeModelDescription.Properties;
                }
            }

            return null;
        }
    }
}

GameScore/Models/GamesBowling.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GameScore.Models
{
    [Serializable]
    public class GamesBowling
    {
        public GamesBowling()
        {

        }

        public IList<Frames> Frame { get; set; }

        public int Score
        {
            get
            {
                int FinalScore = 0;                
                int Count = 0;

                foreach (Frames obj in Frame)
                {
                    int FrameTotal = 0;
                    if (obj.First == 10 || obj.Second == 10)
                    {
                        FrameTotal += 10;

                        for (int i = Count + 1; i <= Frame.Count - 1; i++)
                        {
                            FrameTotal += Frame[i].First;
                            FrameTotal += Frame[i].Second;
                        }
                    }
                    else
                    {
                        FrameTotal += obj.First;
                        FrameTotal += obj.Second;
                    }

                    FinalScore += FrameTotal;

                    Count++;
                }
                return FinalScore;
            }
        }
    }

    [Serializable]
    public class Frames
    {
        public Frames()
        {
            First = 0;
            Second = 0;
        }
        public int First { get; set; }
        public int Second { get; set; }
    }
}

GameScore/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using GameScore.Areas.HelpPage.ModelDescriptions;
using GameScore.Areas.HelpPage.Models;

namespace GameScore.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

GameScore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GameScore.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }
    }
}

GameScore/Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using GameScore.Models;
using Newtonsoft.Json;

namespace GameScore.Controllers
{
    public class ValuesController : ApiController
    {
        [HttpPost]
        [Route("api/Values/GetScore")]
        public int GetScore(object value)
        {
            GamesBowling gameObj = null;
            try
            {
                string json = JsonConvert.SerializeObject(value);

                gameObj = new GamesBowling
                {
                    Frame = JsonConvert.DeserializeObject<IList<Frames>>(json)
                };
            }
            catch (Exception e)
            {
                //error log
                throw e;
            }

            if (gameObj == null)
                return 0;
            else
                return gameObj.Score;
        }
    }
}

GameScore/Views/Home/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.1/angular.min.js"></script>
    <script src="~/Assets/js/controllers.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>

</head>
<body>
    <div ng-app="myApp" ng-controller="scoreCtrl">
        <form class="form-horizontal">
            <div class="modal-header">
                <h4 class="modal-title" id="add-modal-label">Ten Pin Bowling Score Calculator</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="add-firstname" class="col-sm-2 control-label">Score 1</label>
                    <div class="col-sm-10">
                        <input type="number" min="0" max="10" class="form-control" id="add-firstname" name="firstname" placeholder="Score" ng-model="scoreFirst" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="add-lastname" class="col-sm-2 control-label">Score 2</label>
                    <div class="col-sm-10">
                        <input type="number" min="0" max="10" class="form-control" id="add-lastname" name="lastName" placeholder="Score" ng-model="scoreSecond" required>
                    </div>
                </div>
                <div style="margin-left:17%">
                    <button type="submit" class="btn btn-primary" ng-click="onAdd()">Save</button>
                </div>
            </div>
        </form>
        <div>
            Final Score: {{scoreFinal}}
        </div>
        <table class="table table-bordred table-striped" style="width:58%">
            <tr>
                <th>Serial</th>
                <th>Score 1</th>
                <th>Score 2</th>
            </tr>
            <tr ng-repeat="x in frames">
                <td>{{$index+1}}</td>
                <td>{{x.First}}</td>
                <td>{{x.Second}}</td>
            </tr>
        </table>
    </div>
</body>
</html>

GameScore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Bowling Scorer", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>